# Generated by Django 5.1.6 on 2025-03-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='created_at',
        ),
    ]
